Website = "https://github.com/highdoping/FontLoaderSubRe"
Email   = "highdoping@gmail.com"

[Details]
  Icon    = "../resources/icon.png"
  Name    = "FontLoaderSubRe"
  ID      = "com.highdoping.fontloadersubre"
  Version = "0.2.2"
  Build   = 1
  [Details.Release]
    License = "GPLv2"
